import { registerScenario } from "@golem/testkit";

export const scenarios = [
	registerScenario({
		id: "codex-direct-seamless-integration",
		journey: "J2",
		tier: "integration",
		regression: "plain installed Codex loses canonical project/session lifecycle, restart-safe generation identity, or truthful pull-only capability",
	}),
	registerScenario({
		id: "codex-managed-delivery-crash-matrix",
		journey: "J3",
		tier: "integration",
		regression: "managed Codex App Server lifecycle, canonical thread resume, fenced delivery idempotency, and unsupported-provider pre-spawn rejection drift",
	}),
	registerScenario({
		id: "project-identity-git-worktree-relocation",
		journey: "J2",
		tier: "integration",
		regression: "nested Git paths, linked worktrees, relocation, and broad-root heuristics split or merge project identity",
	}),
	registerScenario({
		id: "project-register-concurrency",
		journey: "J2",
		tier: "integration",
		regression: "duplicate real producer registrations allocate multiple project UUIDs or lose durable location/outbox evidence",
	}),
	registerScenario({
		id: "cross-harness-session-lifecycle",
		journey: "J2",
		tier: "integration",
		regression: "cross-harness session generations, terminal lifecycle, aliases, and actor-vs-observation projections drift or resurrect",
	}),
	registerScenario({
		id: "session-reorder-restart-replay",
		journey: "J2",
		tier: "integration",
		regression: "delayed, duplicate, reordered, and restarted logical session facts fail to converge byte-for-byte",
	}),
	registerScenario({
		id: "endpoint-fence-concurrency-crash",
		journey: "J2",
		tier: "integration",
		regression: "concurrent endpoint claims, stale owners, expiry, or reconnect can create duplicate live routes or reuse a fence",
	}),
	registerScenario({
		id: "readiness-capability-matrix",
		journey: "J2",
		tier: "integration",
		regression: "health, readiness, capability qualification, or delivery eligibility can drift from canonical endpoint facts",
	}),
	registerScenario({
		id: "claude-lifecycle-channel-recovery",
		journey: "J4",
		tier: "integration",
		regression: "Claude lifecycle signals, fenced channel authentication, addressed consumption, and unqualified delivery can drift apart",
	}),
	registerScenario({
		id: "live-history-diagnostics",
		journey: "J2",
		tier: "integration",
		regression: "canonical runtime live/history/diagnostic projections lose lifecycle, endpoint, observation, redaction, or restart facts",
	}),
	registerScenario({
		id: "projection-ws-restart-resync",
		journey: "J6",
		tier: "integration",
		regression: "authenticated scoped projection WebSocket snapshots, opaque invalidations, cursors, compaction/policy/restart resync, or project revisions diverge from the HTTP read model",
	}),
	registerScenario({
		id: "dashboard-runtime-lifecycle",
		journey: "J8",
		tier: "integration",
		regression: "the built operator dashboard combines compatibility rows, shows terminal generations live, mutates actor activity on read, leaks diagnostics, or stretches/duplicates passport cards",
	}),
	registerScenario({
		id: "dashboard-disconnect-resync",
		journey: "J8",
		tier: "integration",
		regression: "a dashboard-visible runtime projection reconnects across a control-plane instance restart without a canonical snapshot resync",
	}),
	registerScenario({
		id: "cli-command-parity",
		journey: "J5",
		tier: "pr",
		regression: "typed command registry or legacy-compatible CLI grammar drifts, exposes launch, or writes state during help/schema generation",
	}),
	registerScenario({
		id: "domain-replay",
		journey: "J2",
		tier: "pr",
		regression: "cross-harness identity, lifecycle, ordering, fencing, or readiness drift creates ghosts or stale owners",
	}),
	registerScenario({
		id: "launcher-resolution-matrix",
		journey: "J7",
		tier: "pr",
		regression: "launch precedence, capability qualification, or JSONC preservation drifts before process spawn",
	}),
	registerScenario({
		id: "launcher-launchability-delivery-split",
		journey: "J7",
		tier: "pr",
		regression: "a launchable process is rejected by unqualified delivery evidence or an unqualified delivery path is advertised as push-ready",
	}),
	registerScenario({
		id: "compact-launch-dry-run-matrix",
		journey: "J7",
		tier: "pr",
		regression: "the built resolver/CLI bridge disagrees with launchability and delivery truth or leaks credential/path state",
	}),
	registerScenario({
		id: "compact-launcher-matrix",
		journey: "J5",
		tier: "integration",
		regression: "daily compact launcher grammar, picker, preset persistence, completions, safe aliases, or compatibility shims drift from qualified resolver truth",
	}),
	registerScenario({
		id: "direct-launch-retains-integration",
		journey: "J5",
		tier: "integration",
		regression: "compact launcher changes replace, bypass, or weaken the installed native direct-Codex lifecycle integration",
	}),
	registerScenario({
		id: "migration-dry-run-ambiguity",
		journey: "J7",
		tier: "integration",
		regression: "a legacy audit mutates a supplied home or auto-merges unsafe, corrupt, name/PID, or ambiguous identity evidence",
	}),
	registerScenario({
		id: "migration-apply-crash-rollback",
		journey: "J7",
		tier: "integration",
		regression: "a stale plan, weak alias, partial canonical import, or generated compatibility projection can become authoritative after a failed migration",
	}),
	registerScenario({
		id: "legacy-compat-projection",
		journey: "J7",
		tier: "integration",
		regression: "a compatibility export reads legacy inputs as authority, loses canonical revision facts, or fails to rebuild after a safe strong-alias import",
	}),
	registerScenario({
		id: "testkit-smoke",
		journey: "J3",
		tier: "pr",
		regression: "child restart loses SQLite-backed state or leaks a process group",
	}),
	registerScenario({
		id: "testkit-fake-harness",
		journey: "J5",
		tier: "pr",
		regression: "native harness argv, stdin, crash, duplicate output, or signal handling drifts",
	}),
	registerScenario({
		id: "native-spawn-safety",
		journey: "J5",
		tier: "integration",
		regression: "recursive or unsafe binary discovery, shell expansion, secret leakage, signal loss, or a leaked native child group",
	}),
	registerScenario({
		id: "launcher-signal-cleanup",
		journey: "J5",
		tier: "integration",
		regression: "signal, resize, timeout, or native descendant cleanup leaves an orphaned or misreported harness process",
	}),
	registerScenario({
		id: "testkit-semantic-parity",
		journey: "J6",
		tier: "pr",
		regression: "volatile observations hide a changed readiness or identity fact",
	}),
	registerScenario({
		id: "testkit-cleanup-drill",
		journey: "J3",
		tier: "integration",
		regression: "a failed assertion leaks child descendants or writes outside a temporary home",
	}),
	registerScenario({
		id: "sqlite-owner-migration-recovery",
		journey: "J3",
		tier: "pr",
		regression: "two SQLite writers, migration drift, or a crash loses a committed runtime event or makes tracker recovery unsafe",
	}),
	registerScenario({
		id: "materializer-crash-matrix",
		journey: "J3",
		tier: "pr",
		regression: "concurrent runtime producers, a killed materializer, or duplicate delivery loses canonical state or emits a second outbox effect",
	}),
	registerScenario({
		id: "dashboard-down-inbox-replay",
		journey: "J1",
		tier: "pr",
		regression: "a temporary management/tracker outage drops durable runtime work instead of bounded, idempotent replay",
	}),
	registerScenario({
		id: "delivery-queue-crash-matrix",
		journey: "J4",
		tier: "pr",
		regression: "a claimed durable envelope can be double-settled, lose a retry, or survive a child crash without replay",
	}),
	registerScenario({
		id: "bus-offline-replay",
		journey: "J4",
		tier: "pr",
		regression: "offline subscriptions lose ordered cursor replay, passive slots start unsolicited turns, or pruning drops manual interest",
	}),
	registerScenario({
		id: "tracker-core-compatibility",
		journey: "J4",
		tier: "pr",
		regression:
			"a tracker core extraction loses display ids, phase artifacts, transactional audit/outbox, or MCP-compatible ticket/comment/link/stream semantics",
	}),
	registerScenario({
		id: "tracker-fresh-db-transition",
		journey: "J4",
		tier: "pr",
		regression: "a managed fresh or upgraded tracker schema omits canonical comment dispatch evidence and makes a normal create/update/transition transaction fail after the service has committed other work",
	}),
	registerScenario({
		id: "tracker-http-mcp-parity",
		journey: "J6",
		tier: "integration",
		regression: "bearer and MCP ticket dispatch can select a caller target, disagree with browser disposition, write legacy dispatch_queue, or report failure as command-time settlement",
	}),
	registerScenario({
		id: "durable-command-idempotency-cas",
		journey: "J4",
		tier: "integration",
		regression: "a durable command receipt loses an original typed outcome across a full restart, re-runs a side effect on replay, accepts a stale CAS, or fails to detect an idempotency-key reuse with a differing payload",
	}),
	registerScenario({
		id: "durable-command-idempotency-cas",
		journey: "J4",
		tier: "integration",
		regression: "a restarted control plane replays a durable command receipt with the byte-equivalent original outcome, a stale CAS leaves tracker/audit/outbox unchanged, and a reused idempotency key with a differing payload returns 409 command.idempotency_mismatch",
	}),
	registerScenario({
		id: "committed-outbox-all-write-paths",
		journey: "J6",
		tier: "integration",
		regression: "a committed tracker, management, asset, delivery, bearer, MCP, or core write can omit an opaque scoped invalidation, or a stale/rejected/rolled-back write can emit one",
	}),
	registerScenario({
		id: "browser-principal-scope-authority",
		journey: "J6",
		tier: "integration",
		regression: "browser cookies, bearer/MCP callers, or internal adapters can forge principal scope, survive revocation, or disclose a foreign project",
	}),
	registerScenario({
		id: "browser-control-client-resync",
		journey: "J6",
		tier: "integration",
		regression: "browser client callers can supply authority, merge invalidation deltas, publish stale epochs, change command keys, or retain truth across conflict, gap, restart, and disconnect",
	}),
	registerScenario({
		id: "browser-work-opaque-projection",
		journey: "J4",
		tier: "integration",
		regression: "browser work projections, detail, assets, or scoped invalidations expose unbounded prose, cross-scope identifiers, or a bearer-compatible browser surface",
	}),
	registerScenario({
		id: "browser-work-command-authority",
		journey: "J6",
		tier: "integration",
		regression: "browser work commands bypass durable CSRF/policy/CAS/idempotency authority, reflect command prose, or implement dispatch before GOL-82",
	}),
	registerScenario({
		id: "browser-tracker-delivery-parity",
		journey: "J4",
		tier: "integration",
		regression: "browser dispatch can bypass canonical ticket recipient/generation/fence truth, create a shadow queue, duplicate after restart, claim settlement before a real callback, or leave scoped HTTP refetch without safe receipt/envelope truth",
	}),
	registerScenario({
		id: "browser-control-authority-dispatch",
		journey: "J4",
		tier: "integration",
		regression: "the real browser control surface can bypass same-origin cookie/CSRF authority, target delivery directly, duplicate a replayed dispatch, or claim settlement before canonical delivery callbacks",
	}),
	registerScenario({
		id: "browser-control-restart-resync",
		journey: "J6",
		tier: "integration",
		regression: "the real browser control surface can retain stale truth after a compacted cursor or control-plane restart, disclose scoped authority facts, or retain success artifacts",
	}),
	registerScenario({
		id: "tracker-dispatch-ui",
		journey: "J4",
		tier: "integration",
		regression: "the typed dashboard can merge legacy tracker state, lose conflict drafts, bypass revision authority, target delivery directly, or report enqueueing as settlement",
	}),
	registerScenario({
		id: "roles-gates-ideas-ui",
		journey: "J6",
		tier: "integration",
		regression: "the typed dashboard can fake unavailable roles or ideas, lose a human gate, hide communication settlement, or flatten spec relationships",
	}),
	registerScenario({
		id: "delivery-api-fence-recheck",
		journey: "J4",
		tier: "integration",
		regression: "durable delivery claims skip the canonical endpoint generation/fence/readiness recheck before adapter transport",
	}),
	registerScenario({
		id: "pi-next-turn-crash-replay",
		journey: "J4",
		tier: "integration",
		regression: "Pi next-turn delivery injects without a user turn, loses a crashed claim, double-settles, or renders after its canonical fence changed",
	}),
	registerScenario({
		id: "pi-hostile-diagnostics",
		journey: "J4",
		tier: "integration",
		regression: "Pi dead-letter/retry diagnostics, typed API failures, or rendered extension events retain bearer credentials, tokens, prompt text, or private paths",
	}),
	registerScenario({
		id: "testkit-browser",
		journey: "J8",
		tier: "release",
		regression: "browser checks reuse a signed-in profile or retain success artifacts",
	}),
	registerScenario({
		id: "control-plane-auth-ws-lifecycle",
		journey: "J6",
		tier: "integration",
		regression: "the typed control plane accepts an unsafe caller, loses revision resync, serves no dashboard shell, or leaks its service lock",
	}),
	registerScenario({
		id: "roles-gates-ideas-controls",
		journey: "J6",
		tier: "integration",
		regression: "typed management roles, human gates, idea promotion, and idempotent controls lose audit or restart state",
	}),
	registerScenario({
		id: "ticket-assets-security",
		journey: "J6",
		tier: "integration",
		regression: "ticket-bound assets escape the configured store, leak paths, or fail restart and authorization checks",
	}),
	registerScenario({
		id: "ws-gap-resync",
		journey: "J6",
		tier: "pr",
		regression: "a resumed dashboard stream applies a partial gap instead of refetching one authoritative projection",
	}),
	registerScenario({
		id: "legacy-parity-baseline",
		journey: "J4",
		tier: "integration",
		regression: "legacy dashboard/SQLite/REST/WebSocket/MCP dispatch parity disappears before cutover",
	}),
	registerScenario({
		id: "render-mcp-closure",
		journey: "J1",
		tier: "integration",
		regression: "a render drifts, clobbers a tampered target, rolls back poorly, or ships an MCP that needs the checkout dependency tree",
	}),
	registerScenario({
		id: "opencode-provider-coexistence",
		journey: "J5",
		tier: "integration",
		regression: "OpenCode provider setup clobbers user providers or reports one provider as qualified for another's model/delivery facts",
	}),
	registerScenario({
		id: "opencode-resume-bridge-recovery",
		journey: "J5",
		tier: "integration",
		regression: "OpenCode bridge retries after a crash, loses its fence, or dispatches child/stale generations",
	}),
	registerScenario({
		id: "opencode-direct-canonical-ingress",
		journey: "J5",
		tier: "integration",
		regression: "normal direct OpenCode launch loses authenticated canonical ingress/project registration or permits an unfenced prompt to bypass generation eligibility",
	}),
];
