/**
 * Public persistence boundary. Full writable runtime/tracker ownership remains
 * private to control-plane composition; the only opener here is the narrow,
 * migration-neutral tracker attachment used after the legacy tracker opener.
 */
export { runtimeMigrations, trackerMigrations } from "./schema.js";
export type { TrackerCoreCapabilityHandle } from "./tracker-core-capability.js";
export { openTrackerCoreCapability } from "./tracker-core-capability.js";
export type {
	CapabilityQualification,
	ClaimedOutboxRecord,
	ClaimedTrackerDeliveryEnvelope,
	ClaimedTrackerPassiveBatch,
	CommandStatus,
	DatabaseHealth,
	DatabaseScope,
	DeliveryEnvelopeStatus,
	DeliveryMode,
	DryRunEvidence,
	EndpointControlState,
	EndpointLifecycleState,
	EndpointReadinessState,
	EndpointRouteKind,
	GenerationLifecycleState,
	Harness,
	MigrationDecision,
	MigrationDefinition,
	MigrationMode,
	MigrationPlan,
	MigrationResult,
	MigrationRunStatus,
	PersistenceBoundary,
	PersistenceClock,
	PersistenceOpenOptions,
	PersistencePaths,
	PersistenceStatus,
	PersistenceWriteCapability,
	ProjectIdentitySource,
	ProjectLocationRelation,
	ProjectLocationStatus,
	RuntimeCanonicalMutation,
	RuntimeEndpointCapability,
	RuntimeEndpointEligibility,
	RuntimeEndpointMutationResult,
	RuntimeEndpointStorage,
	RuntimeEndpointView,
	RuntimeFailpoint,
	RuntimeMaterializationInput,
	RuntimeMaterializationResult,
	RuntimeOutboxFailure,
	RuntimeOutboxHealth,
	RuntimeProjectLocationInput,
	RuntimeProjectLocationView,
	RuntimeProjectObservationInput,
	RuntimeProjectObservationResult,
	RuntimeProjectStorage,
	RuntimeProjectView,
	RuntimeSessionAliasInput,
	RuntimeSessionApplyInput,
	RuntimeSessionApplyResult,
	RuntimeSessionCommandContext,
	RuntimeSessionDisposition,
	RuntimeSessionGenerationView,
	RuntimeSessionStorage,
	RuntimeSessionView,
	RuntimeTransactionInput,
	RuntimeTransactionResult,
	SchemaVersionedProvenance,
	SessionAliasKind,
	TrackerAppendBusEventResult,
	TrackerBusEvent,
	TrackerCoreActorContext,
	TrackerCoreAuditRecord,
	TrackerCoreComment,
	TrackerCoreExceptionalClose,
	TrackerCoreLink,
	TrackerCoreLinkRelation,
	TrackerCoreMutationMetadata,
	TrackerCorePhaseEvidence,
	TrackerCorePriority,
	TrackerCoreResourceType,
	TrackerCoreRuntimeReference,
	TrackerCoreState,
	TrackerCoreStorageCapability,
	TrackerCoreStream,
	TrackerCoreWorkItem,
	TrackerCoreWorkItemKind,
	TrackerCreateEnvelopeResult,
	TrackerDeliveryEligibility,
	TrackerDeliveryEnvelope,
	TrackerJsonObject,
	TrackerPendingSubscriptionEvents,
	TrackerStorageCapability,
	TrackerSubscription,
} from "./types.js";
export {
	PersistenceMigrationError,
	PersistenceOwnerConflictError,
	RuntimeFailpointError,
} from "./types.js";

import { runtimeMigrations, trackerMigrations } from "./schema.js";

export const persistenceMigrations = Object.freeze({
	runtime: runtimeMigrations.map(({ id, checksum }) => ({ id, checksum })),
	tracker: trackerMigrations.map(({ id, checksum }) => ({ id, checksum })),
});
